// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9NRAdvWoL6gCDWAJlfPyAj38wJGMHLeE',
    appId: '1:111974334105:web:d092da79777eacf2194208',
    messagingSenderId: '111974334105',
    projectId: 'faccat-recicla-mais',
    authDomain: 'faccat-recicla-mais.firebaseapp.com',
    storageBucket: 'faccat-recicla-mais.firebasestorage.app',
    measurementId: 'G-RN6Y8LMQMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl72yOvhZODLgmmQ_uVS09zZhrPEMO6Hk',
    appId: '1:111974334105:android:3758afc58282f34e194208',
    messagingSenderId: '111974334105',
    projectId: 'faccat-recicla-mais',
    storageBucket: 'faccat-recicla-mais.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAawiERQ9JYIefMddUD3aUMR8rBMJrguVE',
    appId: '1:111974334105:ios:55c178620a74d1cc194208',
    messagingSenderId: '111974334105',
    projectId: 'faccat-recicla-mais',
    storageBucket: 'faccat-recicla-mais.firebasestorage.app',
    iosClientId: '111974334105-36h92cjba8qegp835estv924suemu2so.apps.googleusercontent.com',
    iosBundleId: 'com.example.reciclamais',
  );
}
